language: node_js
node_js:
  - node
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - iojs
  - '3'
  - '2'
  - '1.8'
  - '1.0'
  - '0.12'
  - '0.11'
matrix:
  include:
    - node_js: node
      env: AVRO_COVERAGE=1
before_script:
  - ./scripts/travis install
script:
  - ./scripts/travis test
