language: node_js
node_js:
  # Note that the latest version (node) is handled by the coverage run,
  # included in the matrix below.
  - '11'
matrix:
  include:
    - node_js: node
      env:
        - AVRO_COVERAGE=1
        - COVERALLS_PARALLEL=true
before_script:
  - ./scripts/travis install
script:
  - ./scripts/travis test
notifications:
  # For parallel coverall builds.
  webhooks: https://coveralls.io/webhook
